### PR TITLE
Added `process_file` function

### PR DESCRIPTION
**Pull request by ehsteve**
Also added first draft of code to parse nemisis science packets. This depends on the [issue](https://github.com/ddasilva/ccsdspy/issues/48) in CCSDSPy being solved.

### CODE REVIEW

**Comment by ehsteve** [comment]
Once this is in good shape. I can make similar changes across all of the instrument packages.

**Comment by ehsteve** [comment]
The only thing failing is a small loss in coverage which should not stop this merge request. Is there a way to stop codecov from complaining on small losses to coverage?

**Comment by dbarrous** [comment]
> The only thing failing is a small loss in coverage which should not stop this merge request. Is there a way to stop codecov from complaining on small losses to coverage?

I've adjusted the threshold for it to fail only if there is a change that if it decreases coverage by 5%. It can be adjusted in the Global YAML file here: https://app.codecov.io/account/gh/HERMES-SOC/yaml/

**Comment by ehsteve** [comment]
Thanks @dbarrous!

**Review by dbarrous — APPROVED** [review]
@ehsteve I just finished testing this on the processing lambda function and was able to successfully create files from l0 -> l1 -> ql. It looks like it's working great :) Once we get this merged I'll create a PR for the changes to the processing function to support it. I've also been able to reduce the amount of code needed with this new functionality in the processing function.

**Pull request merged**
